version: '3.5'
services:
  app:
    build: .
    container_name: activity
    command: npm run dev
    image: activity:latest
    ports:
      - '3000:3000'
      - '5173:5173'
    volumes:
      - .:/app